name: event_manager
description: A new Flutter project.

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_slider: ^2.0.1
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/intro/
    - images/auth/

  fonts:
    - family: SF
      fonts:
        - asset: fonts/SF-pro-text.ttf
